In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

In [3]:
kdd = pd.read_csv('../../Data/kddcup.data_10_percent_corrected',header=None )

In [4]:
len(kdd)

494021

In [5]:
kdd.shape

(494021, 42)

In [6]:
apple = ('kddcup.names.txt')

'kddcup.names.txt'

In [88]:
kdd.head()

0    1     2   3    4     5   6   7   8   9    ...     32   33   34    35  \
0   0  tcp  http  SF  181  5450   0   0   0   0   ...      9  1.0  0.0  0.11   
1   0  tcp  http  SF  239   486   0   0   0   0   ...     19  1.0  0.0  0.05   
2   0  tcp  http  SF  235  1337   0   0   0   0   ...     29  1.0  0.0  0.03   
3   0  tcp  http  SF  219  1337   0   0   0   0   ...     39  1.0  0.0  0.03   
4   0  tcp  http  SF  217  2032   0   0   0   0   ...     49  1.0  0.0  0.02   

    36   37   38   39   40       41  
0  0.0  0.0  0.0  0.0  0.0  normal.  
1  0.0  0.0  0.0  0.0  0.0  normal.  
2  0.0  0.0  0.0  0.0  0.0  normal.  
3  0.0  0.0  0.0  0.0  0.0  normal.  
4  0.0  0.0  0.0  0.0  0.0  normal.  

[5 rows x 42 columns]

In [93]:
with open('kddcup.names.txt') as f:
    reader = csv.reader(f,delimiter = ':')
    class_label = next(reader,None)
    #print(class_label)
    headerRow = [column[0] for column in reader]
    headerRow = headerRow+['classLabel']
    kdd = pd.read_csv('kddcup.data_10_percent_corrected',header=None)
    kdd.columns=headerRow

### Preliminary Exploration

In [97]:
kdd['classLabel'].unique()

array(['normal.', 'buffer_overflow.', 'loadmodule.', 'perl.', 'neptune.',
       'smurf.', 'guess_passwd.', 'pod.', 'teardrop.', 'portsweep.',
       'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.', 'satan.',
       'phf.', 'nmap.', 'multihop.', 'warezmaster.', 'warezclient.',
       'spy.', 'rootkit.'], dtype=object)

In [100]:
kdd.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'classLabel'],
      dtype='object')

In [101]:
kdd.duration.unique()

array([   0,    1,   79, ..., 2695, 2751,  120])

In [136]:
groupClassLabel = kdd.groupby('classLabel').count()['duration'].sort_values(ascending = False)

#groupClassLabel.sort_values('duration', ascending=False, axis =1)


In [137]:
groupClassLabel

classLabel
smurf.              280790
neptune.            107201
normal.              97278
back.                 2203
satan.                1589
ipsweep.              1247
portsweep.            1040
warezclient.          1020
teardrop.              979
pod.                   264
nmap.                  231
guess_passwd.           53
buffer_overflow.        30
land.                   21
warezmaster.            20
imap.                   12
rootkit.                10
loadmodule.              9
ftp_write.               8
multihop.                7
phf.                     4
perl.                    3
spy.                     2
Name: duration, dtype: int64

In [ ]:
### correlation between these three
### select correlation using [:1] to select row so that we can have focused correlation
### Check for online solutions where the data is arranged with no correct trace size
### can we take a compartive view of other datasets (look at evolution of the datasets)
###

In [ ]:
### Select 
## 1. smurf.
## 2. neptune.
## 3. normal.
##  generalize them into their attacks

## Preprocessing. 
## Need to labelEncode them

## Feature selection

Feature selection is a process where you automatically select those features in your data that contribute most to the prediction variable or output in which you are interested.

Having too many irrelevant features in your data can decrease the accuracy of the models. Three benefits of performing feature selection before modeling your data are:

Reduces Overfitting: Less redundant data means less opportunity to make decisions based on noise.
Improves Accuracy: Less misleading data means modeling accuracy improves.
Reduces Training Time: Less data means that algorithms train faster.
Two different feature selection methods provided by the scikit-learn Python library are Recursive Feature Elimination and feature importance ranking.

**Do you have domain knowledge?** If yes, construct a better set of ad hoc”” features

**Are your features commensurate?** If no, consider normalizing them.

**Do you suspect interdependence of features?** If yes, expand your feature set by constructing conjunctive features or products of features, as much as your computer resources allow you.

**Do you need to prune the input variables** (e.g. for cost, speed or data understanding reasons)? If no, construct disjunctive features or weighted sums of feature

**Do you need to assess features individually** (e.g. to understand their influence on the system or because their number is so large that you need to do a first filtering)? If yes, use a variable ranking method; else, do it anyway to get baseline results.

**Do you need a predictor?** If no, stop
Do you suspect your data is “dirty” (has a few meaningless input patterns and/or noisy outputs or wrong class labels)? If yes, detect the outlier examples using the top ranking variables obtained in step 5 as representation; check and/or discard them.

**Do you know what to try first?** If no, use a linear predictor. Use a forward selection method with the “probe” method as a stopping criterion or use the 0-norm embedded method for comparison, following the ranking of step 5, construct a sequence of predictors of same nature using increasing subsets of features. Can you match or improve performance with a smaller subset? If yes, try a non-linear predictor with that subset.

**Do you have new ideas, time, computational resources, and enough examples?** If yes, compare several feature selection methods, including your new idea, correlation coefficients, backward selection and embedded methods. Use linear and non-linear predictors. Select the best approach with model selection

**Do you want a stable solution (to improve performance and/or understanding)?** If yes, subsample your data and redo your analysis for several “bootstrap”.

In [145]:

# Recursive Feature Elimination
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load the iris datasets
dataset = datasets.load_iris()
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(dataset.data, dataset.target)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)


from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisiticRegression

dataset = datasets.load_iris() 
#kdd

model = LogisticRegession()
rfe = RFE(model,3)

rfe = rfe.fit(dataset.data, dataset.target)
## Split dataset get only truth value . 
## Do some 

[False  True  True  True]
[2 1 1 1]


In [146]:
kdd.head()

duration protocol_type service flag  src_bytes  dst_bytes  land  \
0         0           tcp    http   SF        181       5450     0   
1         0           tcp    http   SF        239        486     0   
2         0           tcp    http   SF        235       1337     0   
3         0           tcp    http   SF        219       1337     0   
4         0           tcp    http   SF        217       2032     0   

   wrong_fragment  urgent  hot     ...      dst_host_srv_count  \
0               0       0    0     ...                       9   
1               0       0    0     ...                      19   
2               0       0    0     ...                      29   
3               0       0    0     ...                      39   
4               0       0    0     ...                      49   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   
1                     1.0                     0.0   
2                     1.0                     0.0   
3                     1.0                     0.0   
4                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                          0.0   
1                         0.05                          0.0   
2                         0.03                          0.0   
3                         0.03                          0.0   
4                         0.02                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  classLabel  
0                       0.0     normal.  
1                       0.0     normal.  
2                       0.0     normal.  
3                       0.0     normal.  
4                       0.0     normal.  

[5 rows x 42 columns]

In [ ]:
## columns with the labeled data:
## protocol_type
## service
## flag
## land
## Logged in
## is host login
## is guest login
## 

## once we are done with fitting ## perhaps we can create new rules to show from decision tree of how much
## of these attribute have effect

In [182]:
kdd.protocol_type.unique()

array(['tcp', 'udp', 'icmp'], dtype=object)

In [183]:
kdd.service.unique()

array(['http', 'smtp', 'finger', 'domain_u', 'auth', 'telnet', 'ftp',
       'eco_i', 'ntp_u', 'ecr_i', 'other', 'private', 'pop_3', 'ftp_data',
       'rje', 'time', 'mtp', 'link', 'remote_job', 'gopher', 'ssh',
       'name', 'whois', 'domain', 'login', 'imap4', 'daytime', 'ctf',
       'nntp', 'shell', 'IRC', 'nnsp', 'http_443', 'exec', 'printer',
       'efs', 'courier', 'uucp', 'klogin', 'kshell', 'echo', 'discard',
       'systat', 'supdup', 'iso_tsap', 'hostnames', 'csnet_ns', 'pop_2',
       'sunrpc', 'uucp_path', 'netbios_ns', 'netbios_ssn', 'netbios_dgm',
       'sql_net', 'vmnet', 'bgp', 'Z39_50', 'ldap', 'netstat', 'urh_i',
       'X11', 'urp_i', 'pm_dump', 'tftp_u', 'tim_i', 'red_i'],
      dtype=object)

In [184]:
kdd.flag.unique()

array(['SF', 'S1', 'REJ', 'S2', 'S0', 'S3', 'RSTO', 'RSTR', 'RSTOS0',
       'OTH', 'SH'], dtype=object)

In [185]:
kdd.land.unique()

array([0, 1])

In [186]:
kdd.logged_in.unique()

array([1, 0])

In [187]:
kdd.is_host_login.unique()

array([0])

In [188]:
kdd.is_guest_login.unique()

array([0, 1])

In [201]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(kdd.service)
print(le.classes_)
le.transform(kdd.service)

['IRC' 'X11' 'Z39_50' 'auth' 'bgp' 'courier' 'csnet_ns' 'ctf' 'daytime'
 'discard' 'domain' 'domain_u' 'echo' 'eco_i' 'ecr_i' 'efs' 'exec'
 'finger' 'ftp' 'ftp_data' 'gopher' 'hostnames' 'http' 'http_443' 'imap4'
 'iso_tsap' 'klogin' 'kshell' 'ldap' 'link' 'login' 'mtp' 'name'
 'netbios_dgm' 'netbios_ns' 'netbios_ssn' 'netstat' 'nnsp' 'nntp' 'ntp_u'
 'other' 'pm_dump' 'pop_2' 'pop_3' 'printer' 'private' 'red_i'
 'remote_job' 'rje' 'shell' 'smtp' 'sql_net' 'ssh' 'sunrpc' 'supdup'
 'systat' 'telnet' 'tftp_u' 'tim_i' 'time' 'urh_i' 'urp_i' 'uucp'
 'uucp_path' 'vmnet' 'whois']


array([22, 22, 22, ..., 22, 22, 22])

In [174]:

# #X and y
# # X is a set of variables with X all attributes but class label
# # Y is all attributes 
# from sklearn.ensemble import ExtraTreesClassifier
# from sklearn.model_selection import train_test_split

# X = np.array(kdd.drop('classLabel', axis = 1))
# y = np.array(kdd['classLabel'])

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)



ValueError: could not convert string to float: 'SF'

In [179]:
# from sklearn.ensemble import ExtraTreesClassifier
# from sklearn.feature_selection import SelectFromModel

# clf = ExtraTreesClassifier()
# clf = clf.fit(X, y)
# clf.feature_importances_  
# #model = SelectFromModel(clf, prefit=True)
# #X_new = model.transform(X)
# #X_new.shape        

ValueError: could not convert string to float: 'SF'

In [180]:

# #
# ## Correlational plots:
# %matplotlib inline
# #column = ['year','yearReconstructed']
# #dec_lr2016 = dec_lr.loc[dec_lr['year'] == 2016]
# #dec_lr2016.drop(column,axis = 1 ,inplace = True)
# corr = kdd.corr()
# sns.heatmap(corr,annot=True, cmap = 'RdYlGn', linewidth = 0.1)
# fig = plt.gcf()
# fig.set_size_inches(10,8)
# fig=plt.gcf()
# fig.set_size_inches(18,15)
# plt.xticks(fontsize=14)
# plt.yticks(fontsize=14)
# plt.show()

Models:

In [ ]:
# Machine Learning Models

%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import f1_score,confusion_matrix,classification_report
from sklearn.metrics import accuracy_score

# split data train 70 % and test 30 %
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)


#random forest classifier with n_estimators 
clf_rf = RandomForestClassifier()      
clr_rf = clf_rf.fit(X_train,Y_train)

ac = accuracy_score(Y_test,clf_rf.predict(X_test))
print('Accuracy is: ',ac)
cm = confusion_matrix(Y_test,clf_rf.predict(X_test))




In [ ]:
## Support Vector Machine
clf_svc = SVC()
    
clr_svc = clf_svc.fit(X_train,Y_train)
prediction = clf_svc.predict(X_test)
ac = accuracy_score(Y_test,prediction)
print('Accuracy is: ',ac)
cm = confusion_matrix(Y_test,prediction)
sns.heatmap(cm,annot=True,fmt="d")

In [ ]:
## Decision Tree
dtree = DecisionTreeClassifier()
dtree.fit(X_train, Y_train)
predictions = dtree.predict(X_test)
ac = accuracy_score(Y_test,predictions)
print('Accuracy is: ',ac)
cm = confusion_matrix(Y_test, predictions)
sns.heatmap(cm,annot=True,fmt="d")
#print(classification_report(y_test, predictions))

In [ ]:
## Gaussian NB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
predictions_gnb = gnb.predict(X_test)
ac = accuracy_score(Y_test,predictions_gnb)
print('Accuracy is: ',ac)
cm = confusion_matrix(Y_test, predictions_gnb)

sns.heatmap(cm,annot = True , fmt = "d")

In [ ]:
## LinearDiscriminanatAnalysis
ld = LinearDiscriminantAnalysis()
ld.fit(X_train, Y_train)
predictions_ld = ld.predict(X_test)
ac = accuracy_score(Y_test,predictions_ld)
print('Accuracy is: ',ac)
cm = confusion_matrix(Y_test, predictions_ld)
sns.heatmap(cm,annot = True , fmt = "d")

In [138]:
#ten fold cross_validation for more improvement